services:
  consul:
    image: "hashicorp/consul:latest"
    container_name: consul
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: agent -server -bootstrap-expect=1 -node=eis-consul -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui -config-dir=/consul/config
    volumes:
      - "./data:/consul/data"
      - "./config:/consul/config"
    networks:
      - eis-net

networks:
  eis-net:
    external: true