version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: admin@123
    ports:
      - "5432:5432"
    networks:
      - eis-net

networks:
  eis-net:
    external: true
