services:
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    command: ["redis-server", "--requirepass", "admin@123", "--user", "admin", "on"]
    restart: always
    ports:
      - "6379:6379"
    networks:
      - eis-net

networks:
  eis-net:
    external: true